[build]
  command = "npm install --legacy-peer-deps && ESLINT_NO_DEV_ERRORS=true NEXT_DISABLE_ESLINT=1 npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  ESLINT_NO_DEV_ERRORS = "true"
  NEXT_DISABLE_ESLINT = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 